### ISSUE TITLE
Optimize Ledger Performance

### ISSUE THREAD

**Issue by bonedaddy** [RTradeLtd/s3x#6]
Currently the ledger claims write locks anytime an put operation is performed, and read locks anytime a get operation is performed, under significant load it will suffer from performance issues due to the unintelligent mutex locks.

Instead we should enable complete write locks anytime the ledger itself is updated, which only occurs at the end of of a put operation, because before hand we update the corresponding object/bucket ledger entry.  Then when the individual buckets are being altered, we can claim a write lock solely for that bucket. Additionally we can lock individual objects from within the bucket separately.

If implemented properly (whether it be mutex's, atomic, or channel operations) we can ensure that the only time we globally bblock is when the ledger is updated on disk.

**Comment by xiegeo** [comment]
Looking through the code, I believe the interface between xObjects and LedgerStore needs a redesign.

Following the code for xObjects.PutObject for example: 

`x.ledgerStore.BucketExists` calls:
getLedger with read lock

`x.addObjectToBucketAndIPFS` calls :
`bucketFromIPFS` ->  x.ledgerStore.GetBucketHash -> le.getLedger() with read lock

`x.ledgerStore.UpdateBucketHash` calls: 
UpdateBucketHash -> getLedger() and putLedger(ledger) with write lock

` x.ledgerStore.AddObjectToBucket` calls:
AddObjectToBucket -> getLedger() and putLedger(ledger) with write lock

### What are the problems?

Locks are held and released many times within the operation, meaning the ledger state could change between locks.

Bucket hash is saved before object hash. If a crash occurred in between (such as power outage), then the ledger could be saved in an inconsistent state.

Each get and put ledger operation is expensive, and increases linearly with the number of objects.

### What should happen:

A single write lock per bucket over the entire operation. At most one get and one set ledger call per operation. 

The ledger data structure should be split up to take advantage of the datastore's native object lookup capacities. 

Considering we only support a signal master to the ledger (otherwise we need to build it on top of a distributed transactional database). we can cache ledger state without worrying about cache invalidation.

### What helps

A standard unit testing library for minio.ObjectLayer

**Comment by bonedaddy** [comment]
Good work and I agree with your assessment, as well as your proposed solution and keep support to a single master. One thing to keep in mind is that the ledger structure will need to be able to temporarily store information related to multipart uploads. Once the multipart upload is complete, the ledger state information with regards to that multipart upload should be removed.

Feel free to get started on this whenever, however I think now that we are both working on the codebase and touching slightly different parts, we should work in branches instead of directly on master.

edit1:

In terms of a testing library for `minio.ObjectLayer` i have asked about that on the minio slack, however in the meantime we can look into https://github.com/minio/minio/tree/master/mint

**Comment by xiegeo** [comment]
closed by #16
